!
frr version 8.0
frr defaults traditional
hostname frr2
password zebra
!
ip forwarding
!
router bgp 65102
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 neighbor 198.20.12.3 remote-as 65101
 !
 address-family ipv4 unicast
  network 198.20.2.0/24
 exit-address-family
!
line vty
!
